# NixOS Configuration with AAIA - Complete Installation
{ config, pkgs, ... }:

let
  # Import the AAIA flake from /root/aaia
  aaiaFlake = builtins.getFlake "/root/aaia";
in
{
  # Import hardware configuration (generated during installation)
  imports = [
    ./hardware-configuration.nix  # Generated by nixos-generate-config
    aaiaFlake.nixosModules.aaia
  ];

  # Bootloader configuration (required for boot)
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Networking configuration
  networking.hostName = "nixos-aaia";

  # Static IP configuration
  networking.useDHCP = false;
  networking.interfaces.enp0s3 = {  # Change interface name if needed (check with: ip link)
    useDHCP = false;
    ipv4.addresses = [{
      address = "192.168.178.105";
      prefixLength = 24;
    }];
  };
  networking.defaultGateway = "192.168.178.1";
  networking.nameservers = [ "192.168.178.1" "8.8.8.8" ];

  # Time zone
  time.timeZone = "Europe/Berlin";

  # Internationalisation
  i18n.defaultLocale = "en_US.UTF-8";
  i18n.extraLocaleSettings = {
    LC_ADDRESS = "de_DE.UTF-8";
    LC_IDENTIFICATION = "de_DE.UTF-8";
    LC_MEASUREMENT = "de_DE.UTF-8";
    LC_MONETARY = "de_DE.UTF-8";
    LC_NAME = "de_DE.UTF-8";
    LC_NUMERIC = "de_DE.UTF-8";
    LC_PAPER = "de_DE.UTF-8";
    LC_TELEPHONE = "de_DE.UTF-8";
    LC_TIME = "de_DE.UTF-8";
  };

  # Console and X11 keyboard layout - German
  console.keyMap = "de";
  services.xserver.xkb = {
    layout = "de";
    variant = "";
  };

  # User configuration
  users.users.admin = {
    isNormalUser = true;
    description = "Administrator";
    extraGroups = [ "wheel" ];  # wheel = sudo access
    initialPassword = "changeme";  # CHANGE THIS AFTER FIRST LOGIN!
  };

  # Enable SSH access
  services.openssh = {
    enable = true;
    settings = {
      PermitRootLogin = "yes";  # Allow root login (disable in production!)
      PasswordAuthentication = true;
    };
  };

  # Enable AAIA service
  services.aaia = {
    enable = true;
  };

  # Enable experimental features for flakes (required)
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  # Allow unfree packages if needed
  nixpkgs.config.allowUnfree = true;

  # System packages
  environment.systemPackages = with pkgs; [
    # AAIA package
    aaiaFlake.packages.${pkgs.system}.aaia

    # Essential system utilities
    vim
    nano
    git
    htop
    curl
    wget
    tmux
    parted
    gptfdisk
  ];

  # Firewall configuration
  networking.firewall = {
    enable = true;
    allowedTCPPorts = [ 
      22    # SSH
      5080  # AAIA Web-Gui
    ];
  };

  # Logging configuration
  services.journald = {
    extraConfig = ''
      SystemMaxUse=1G
      RuntimeMaxUse=100M
    '';
  };

  # System state version - DO NOT CHANGE after installation
  system.stateVersion = "24.05";

  # Optional: Configure automatic updates
  system.autoUpgrade = {
    enable = false;
    dates = "04:00";
    allowReboot = false;
  };

  # AAIA environment variables
  systemd.services.aaia.environment = {
    AAIA_LOG_LEVEL = "INFO";
  };

  # Create AAIA directories
  systemd.tmpfiles.rules = [
    "d /var/lib/aaia/logs 0755 aaia aaia -"
    "d /var/lib/aaia/data 0755 aaia aaia -"
    "d /var/lib/aaia/config 0755 aaia aaia -"
  ];
}
